#ifndef CLASSES_H
#define CLASSES_H

#define CONVEXSHAPE_TABLE "ConvexShape"
#define TEXTURE_TABLE "Texture"
#define RENDERTEXTURE_TABLE "RenderTexture"
#define GRAPHICS_TABLE "Graphics"
#define WINDOW_TABLE "Window"
#define VIEW_TABLE "View"
#define IMAGE_TABLE "Image"
#define GIF_TABLE "GifImage"
#define FONT_TABLE "Font"
#define REGULARSHAPE_TABLE "RegularShape"
#define SHADER_TABLE "Shader"
#define SPRITE_TABLE "Sprite"
#define TEXT_TABLE "Text"
#define THREAD_TABLE "Thread"
#define VERTEXARRAY_TABLE "VertexArray"
#define UDPSOCKET_TABLE "UdpSocket"
#define TCPSOCKET_TABLE "TcpSocket"
#define TCPLISTENER_TABLE "TcpListener"
#define SOCKETSELECTOR_TABLE "SocketSelector"

#include "Renderwindow.h"
#include "Image.h"
#include "Text.h"
#include "Font.h"
#include "Vertexarray.h"
#include "Rendertexture.h"
#include "Texture.h"
#include "Sprite.h"
#include "Convexshape.h"
#include "Regularshape.h"
#include "View.h"
#include "Shader.h"
#include "Thread.h"
#include "Network.h"
#include "Gif.h"
#include "Graphics.h"

#endif
